# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akwiki < Formula
  desc "Personal wiki static site generator inspired by akngs's wiki"
  homepage "https://github.com/kyungw00k/akwiki"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/akwiki/releases/download/v1.2.0/akwiki_darwin_amd64.tar.gz"
      sha256 "9aa1fcc56586d2c560ed5c4f84e32b6d4f14797806df2a5eff7410d82983a314"

      def install
        bin.install "akwiki"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/akwiki/releases/download/v1.2.0/akwiki_darwin_arm64.tar.gz"
      sha256 "d0c4e6081afb2e8557656a794a0f1807f86ce3703d72a85d2df93da0390a2fb7"

      def install
        bin.install "akwiki"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/akwiki/releases/download/v1.2.0/akwiki_linux_amd64.tar.gz"
        sha256 "7007f07338d5837968812151ce158a94d5d41aaa6851e0a83ec52701469c8659"

        def install
          bin.install "akwiki"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/akwiki/releases/download/v1.2.0/akwiki_linux_arm64.tar.gz"
        sha256 "c74a4f5756aebd92a88d9585892d03b063260dccb2b57e7d6a4197042142a52e"

        def install
          bin.install "akwiki"
        end
      end
    end
  end

  test do
    system "#{bin}/akwiki", "--version"
  end
end
