# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Akwiki < Formula
  desc "Personal wiki static site generator inspired by akngs's wiki"
  homepage "https://github.com/kyungw00k/akwiki"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/akwiki/releases/download/v1.1.0/akwiki_darwin_amd64.tar.gz"
      sha256 "4a03fdb8144ab936a12957bf74dfd2a3d481fe247105aa6898add416e9123dee"

      def install
        bin.install "akwiki"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/akwiki/releases/download/v1.1.0/akwiki_darwin_arm64.tar.gz"
      sha256 "fdb2569210b357e79c7be1f690cf22a9e75c2400281321f39372e8e118b7777c"

      def install
        bin.install "akwiki"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/akwiki/releases/download/v1.1.0/akwiki_linux_amd64.tar.gz"
        sha256 "8b4fe7786f93a4114e6c809537b0d6daf8247eca830132fd8496c08477f1914b"

        def install
          bin.install "akwiki"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/akwiki/releases/download/v1.1.0/akwiki_linux_arm64.tar.gz"
        sha256 "39095474f1fd7e76d72bed3b584fb151ca5b78c2d9edd18cef1c6c23673bfd40"

        def install
          bin.install "akwiki"
        end
      end
    end
  end

  test do
    system "#{bin}/akwiki", "--version"
  end
end
