# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkpure < Formula
  desc "CLI tool to download APK files from APKPure"
  homepage "https://github.com/kyungw00k/apkpure"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/apkpure/releases/download/v1.2.0/apkpure_darwin_amd64.tar.gz"
      sha256 "c5e9a2f89185c9949d41206a1c2ab4e8360b45a2523dc50c15ba6789ecf36c29"

      def install
        bin.install "apkpure"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/apkpure/releases/download/v1.2.0/apkpure_darwin_arm64.tar.gz"
      sha256 "f93671e5ce07629c214070faf3bceaffadfab087151884311b59090bc6caf944"

      def install
        bin.install "apkpure"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/apkpure/releases/download/v1.2.0/apkpure_linux_amd64.tar.gz"
        sha256 "3ed5dbd60cbc0f1a3f12481275de7937e7b9b117052099cc8b9417fca0262b9d"

        def install
          bin.install "apkpure"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/apkpure/releases/download/v1.2.0/apkpure_linux_arm64.tar.gz"
        sha256 "3bbc809bd0ed3d5aab291aa1851d0c170ef2b7a9f1a3f7a1d7989b878e6a1802"

        def install
          bin.install "apkpure"
        end
      end
    end
  end

  test do
    assert_match "apkpure version", shell_output("#{bin}/apkpure -V")
  end
end
