# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apkpure < Formula
  desc "CLI tool to download APK files from APKPure"
  homepage "https://github.com/kyungw00k/apkpure-go"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/apkpure-go/releases/download/v1.1.0/apkpure_darwin_amd64.tar.gz"
      sha256 "8bf3d7aebcd815f9a56c29a2d6886934e8544ac76100168fdde5953aa2cf8e3e"

      def install
        bin.install "apkpure"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/apkpure-go/releases/download/v1.1.0/apkpure_darwin_arm64.tar.gz"
      sha256 "34e423261574ae17f03c1abe07b1ca6e8daef258e0c2d64fc77392bcbd44e331"

      def install
        bin.install "apkpure"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/apkpure-go/releases/download/v1.1.0/apkpure_linux_amd64.tar.gz"
        sha256 "e37402912227a5dcb12e4a94e6e43cbd638eb51e9c9a01ba5ce61b62f6a45510"

        def install
          bin.install "apkpure"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/apkpure-go/releases/download/v1.1.0/apkpure_linux_arm64.tar.gz"
        sha256 "0469195123bc8a5b70e20cc9f0bd0753a4e00b9c8b1add1d0bda5174a91a4abf"

        def install
          bin.install "apkpure"
        end
      end
    end
  end

  test do
    assert_match "apkpure version", shell_output("#{bin}/apkpure -V")
  end
end
