# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbibackend < Formula
  desc "Install local titles into Nintendo Switch via USB"
  homepage "https://github.com/kyungw00k/dbibackend"
  version "1.1.0"
  license "MIT"
  depends_on :macos

  on_arm do
    url "https://github.com/kyungw00k/dbibackend/releases/download/v1.1.0/dbibackend_darwin_arm64.tar.gz"
    sha256 "4057d9086df3bf2c64423c261eadcbf24820c88d8d06f1ebf8503d71de086d19"

    def install
      bin.install "dbibackend"
    end
  end

  test do
    assert_match "dbibackend version", shell_output("#{bin}/dbibackend --version")
  end
end
