# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dbibackend < Formula
  desc "Install local titles into Nintendo Switch via USB"
  homepage "https://github.com/kyungw00k/dbibackend"
  version "1.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.4.1/dbibackend_darwin_amd64.tar.gz"
      sha256 "02aa368b9f36ad7389bcda9bcf9c6c92d70b5cf99c54f84eec9d6a4d388f44fc"

      def install
        bin.install "dbibackend"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/dbibackend/releases/download/v1.4.1/dbibackend_darwin_arm64.tar.gz"
      sha256 "0096b31615688fdb41849d43549d21df0f9296de4f0cee04398e3ed8ad1c08fc"

      def install
        bin.install "dbibackend"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.4.1/dbibackend_linux_amd64.tar.gz"
        sha256 "ba13553715b311ba9b2ceff330dbe9ed7f0b8b34a942572c0c35cd3a825533c2"

        def install
          bin.install "dbibackend"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/dbibackend/releases/download/v1.4.1/dbibackend_linux_arm64.tar.gz"
        sha256 "0760a4b87fcd17192e4a5df814f25f75b8c0b84a1e03e1e9a5e6a0e5facbe726"

        def install
          bin.install "dbibackend"
        end
      end
    end
  end

  test do
    assert_match "dbibackend version", shell_output("#{bin}/dbibackend --version")
  end
end
