# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juso < Formula
  desc "Korean postal code lookup CLI"
  homepage "https://github.com/kyungw00k/juso"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/juso/releases/download/v1.1.0/juso_darwin_amd64.tar.gz"
      sha256 "ee91001b296a529257a78b0fe675a683b755775ce606adef91a4044b7cdd25e5"

      def install
        bin.install "juso"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/juso/releases/download/v1.1.0/juso_darwin_arm64.tar.gz"
      sha256 "4600c8c3b1dada642d32170144bfb7f24eac02d8eccf290b5838222ddaa03700"

      def install
        bin.install "juso"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/juso/releases/download/v1.1.0/juso_linux_amd64.tar.gz"
        sha256 "e5164b205fea175a1c5aa0d0d17215acc013eebff678a784bb6a79267d2f0aac"

        def install
          bin.install "juso"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/juso/releases/download/v1.1.0/juso_linux_arm64.tar.gz"
        sha256 "0515aa5b541c9e38491e2f9e5abea837e66df669d79fb16b716de144ffae61d0"

        def install
          bin.install "juso"
        end
      end
    end
  end

  test do
    assert_match "juso version", shell_output("#{bin}/juso --version")
  end
end
