# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juso < Formula
  desc "Korean postal code lookup CLI"
  homepage "https://github.com/kyungw00k/juso"
  version "1.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/juso/releases/download/v1.2.0/juso_darwin_amd64.tar.gz"
      sha256 "5cda31a53cd63fea5b9732e8efbf78f063972f58b6a3f171086d820e890c86f6"

      def install
        bin.install "juso"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/juso/releases/download/v1.2.0/juso_darwin_arm64.tar.gz"
      sha256 "2e493738e452615b761905442409fe01c895427d85084ea11c78628f93ce5334"

      def install
        bin.install "juso"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/juso/releases/download/v1.2.0/juso_linux_amd64.tar.gz"
        sha256 "ec4e5b80a7725e3e82b9dbf12352ae4385c215b242b70637fa908adcd6c602da"

        def install
          bin.install "juso"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/juso/releases/download/v1.2.0/juso_linux_arm64.tar.gz"
        sha256 "68de097105d67449fe94f33a0c69073a121404faef2f5897757e02fb0f4391a5"

        def install
          bin.install "juso"
        end
      end
    end
  end

  test do
    assert_match "juso version", shell_output("#{bin}/juso --version")
  end
end
