# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sw < Formula
  desc "Stealth Wright - Silent browser automation CLI"
  homepage "https://github.com/kyungw00k/stealth-wright"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/stealth-wright/releases/download/v1.0.0/sw_darwin_amd64.tar.gz"
      sha256 "cfbbf6825e580d9af72b5820a08a59f14e71b02d9ecea5eba7f44c49fb4c8f8b"

      def install
        bin.install "sw"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/stealth-wright/releases/download/v1.0.0/sw_darwin_arm64.tar.gz"
      sha256 "441147bbf040b763690f12d63fdfdeb16f965132dbad115c9518b6cb6ffbe4b9"

      def install
        bin.install "sw"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/stealth-wright/releases/download/v1.0.0/sw_linux_amd64.tar.gz"
        sha256 "2c4838a7edae567733c1822fbdb23c07151095a3d55fcb7dd7b19de4943426e2"

        def install
          bin.install "sw"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/stealth-wright/releases/download/v1.0.0/sw_linux_arm64.tar.gz"
        sha256 "a57f04c8ee566864f1e8b77e213be0670977fe1e5c76067d98b3d315bcdd9853"

        def install
          bin.install "sw"
        end
      end
    end
  end

  test do
    assert_match "sw version", shell_output("#{bin}/sw --version")
  end
end
