# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Upbit < Formula
  desc "AI-native CLI for Upbit cryptocurrency exchange"
  homepage "https://github.com/kyungw00k/upbit"
  version "1.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kyungw00k/upbit/releases/download/v1.1.0/upbit_darwin_amd64.tar.gz"
      sha256 "afa4adf46a2a13ddf122824b603dfaf6fe717b5bf762c281cff9a3ea28ca7cab"

      def install
        bin.install "upbit"
      end
    end
    on_arm do
      url "https://github.com/kyungw00k/upbit/releases/download/v1.1.0/upbit_darwin_arm64.tar.gz"
      sha256 "0eee0cd1e530c4be74d5aa6cc12613cc13641e77b580a58e7c7bfabee408513b"

      def install
        bin.install "upbit"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/upbit/releases/download/v1.1.0/upbit_linux_amd64.tar.gz"
        sha256 "b81383be6ebdc47152c60bb46637765b9e2655d1f807598ff34eed1a74c52662"

        def install
          bin.install "upbit"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kyungw00k/upbit/releases/download/v1.1.0/upbit_linux_arm64.tar.gz"
        sha256 "619b5589babbc64ca59f96c2dfacf17cc8f0ea4f71712306b21d4bc83fbd2a9f"

        def install
          bin.install "upbit"
        end
      end
    end
  end

  test do
    assert_match "upbit version", shell_output("#{bin}/upbit --version")
  end
end
